GET http://localhost:3000/api/users/Alice99/profile HTTP/1.1

###
GET http://localhost:3000/api/users/slkdfjlsdkjf/profile HTTP/1.1

###
###
GET http://localhost:3000/api/games/watch/8d48e371-63df-4fe9-ad41-39241455e594 HTTP/1.1

###

GET http://localhost:3000/api/auth/logout HTTP/1.1
###

GET http://localhost:3000/api/auth/refresh HTTP/1.1

###

GET http://localhost:3000/api/auth/42authURI
###

GET http://localhost:3000/api/users/Alice99/games?skip=-1&take=20&order=dec HTTP/1.1

###
GET http://localhost:3000/api/users/me HTTP/1.1
###
PATCH http://localhost:3000/api/users/2FA?toggle=false HTTP/1.1
###
PATCH http://localhost:3000/api/users/alias HTTP/1.1
content-type: application/json

{
	"alias": "Alice9999"
}
###
PATCH http://localhost:3000/api/users/2FA?toggle=kjhkj HTTP/1.1

###
GET http://localhost:3000/api/users/search?key=a&skip=0&take=20& HTTP/1.1

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "null"
}
###
GET http://localhost:3000/api/auth/2FA/generate HTTP/1.1


###

POST http://localhost:3000/api/auth/2FA/validate HTTP/1.1
content-type: application/json

{
    "code": "148378"
}

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "Alice99",
    "password": "null"
}

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "Alice99",
    "password": "null"
}
###
POST http://localhost:3000/api/chat/3237797f-c7a0-46bb-ae71-5e0544d113d4/join HTTP/1.1
content-type: application/json

{
    "password": ""
}

###

GET http://localhost:3000/api/users/Alice99/profile HTTP/1.1

