GET http://localhost:3000/api/users/Alice99/profile?nb=x HTTP/1.1

###
GET http://localhost:3000/api/users/Awoman HTTP/1.1

###

GET http://localhost:3000/api/auth/refresh HTTP/1.1

###

GET http://localhost:3000/api/users/Alice99/games?skip=0&take=20&order=desc HTTP/1.1

###
GET http://localhost:3000/api/users/me/games?skip=1&take=20&order=asc HTTP/1.1

###
GET http://localhost:3000/api/users/search?key=rasdasdasdasd&skip=0&take=2 HTTP/1.1

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "Alice99",
    "password": "null"
}

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "TrucMuche",
    "password": "superstrongpassword"
}

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "popo",
    "password": "superstrongpassword"
}

###

GET http://localhost:3000/api/auth/refresh HTTP/1.1
