version: '3.0'
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
    driver_opts:
      type:
          none
      device: ${HOME}/goinfre/db_volume
      o: bind
